language: node_js
node_js:
- '10'
script: rollup -c
deploy:
  provider: releases
  api_key:
    secure: qI/XK2cKqjt4Z8bEgQCClP29utSu8c025a+26DKQeC4+TaNCIyUIv4gx3twNtqgthxQcAxesh22cx/pia5AbljKZ4sCtl4AyGDfOKg0efvBWsDFolCx+q/3ED/gon9u43Vf1JMhL+hCp/v1IQWVM2DHXED8LrUFzp4CwsdP9ZAtj1Mgm6pGbnrpJQnRzSImKhs4IOJbZzEnIDTi6q/gdsE+ReCVR5AIPOrZhdkrcZ/dUI2sA01mfOD/ZXIUVlhnaNs9FiS6ztkGlAdjDFPEj7ObqTK4XJp4uweWWFDlNaPEMamV+8l3JVV9YBj2n/wSPbqY7M+dleRC32/Cxi4RNOzs/eiSovTIHrYyDq5E7E71LENj87ZqblmPLZ0fzdcGoVibuJYm6d92eDh4KVYqPFSb+MQj1OOtxFoKKQzVdNjrJPTOGrRjhwOi8tiBTgBCqSiZTrpxX3rh0NISj0eCnJRO+l9nggq2U2Z1Ikpl6WQDmXF+2vACmKzRUsnwVBeuLd488x8HTRwB1JiiPGdCkNLiZRjvXMz/iFnZKETz5bTjUnU9Rz+vIyaZY7qx2K+H0bSjbTNj6rDUEm8YCjwBOu/l2dqBPgg2A39FlttESsUpyd8EaluSa1+L+P7IUveiMzkBKnEm1ERsuLoRq/5iz8DSPU+qZAWfeZqgkrzVPNFw=
  file: "./dist/play.js"
  skip_cleanup: true
  on:
    tags: true
